In [11]:
import numpy as np

In [2]:
liste1 = [1,2,3,4]
array1 = np.array(liste1)
array1

array([1, 2, 3, 4])

In [5]:
print("liste1'in veri tipi: ", type(liste1))
print("array1'in veri tipi: ", type(array1))

liste1'in veri tipi:  <class 'list'>
array1'in veri tipi:  <class 'numpy.ndarray'>


In [6]:

b = np.array([[3,1,7,11],[2,8,13,21]])

print(b)


[[ 3  1  7 11]
 [ 2  8 13 21]]


#### Numpy Giriş

In [7]:
a = np.array([[1,3,5],[4,6,8]])
print(a)

[[1 3 5]
 [4 6 8]]


In [10]:
print("Dizinin Boyutu:", a.shape)# (satır sayısı,sütun sayısı -> 2 x 3 matris)
print("Uzunluk: ", len(a)) # (uzunluk -> satır sayısı
print("Boyutu: ", a.ndim) # (dizinin boyutu)
print("Kaç elemanlı: ", a.size) # (eleman sayısı)
print("Verilerin Tipi: ", a.dtype.name) # (girdilerin tipi)

Dizinin Boyutu: (2, 3)
Uzunluk:  2
Boyutu:  2
Kaç elemanlı:  6
Verilerin Tipi:  int32


2

In [6]:
a.ndim # (dizinin boyutu)

2

In [7]:
a.size # (eleman sayısı)

6

In [9]:
a.dtype.name # (girdilerin tipi)

'int32'

In [12]:
a = a.astype(float)
a

array([[1., 3., 5.],
       [4., 6., 8.]])

In [13]:
a.dtype

dtype('float64')

In [15]:
np.array_equal(a,b)

False

In [16]:
a<2

array([[ True, False, False],
       [False, False, False]])

In [17]:
b

array([[ 3,  1,  7, 11],
       [ 2,  8, 13, 21]])

In [18]:
b.max(axis=0)

array([ 3,  8, 13, 21])

In [19]:
b.cumsum(axis=0)

array([[ 3,  1,  7, 11],
       [ 5,  9, 20, 32]], dtype=int32)

In [23]:
np.std(b)

6.2599920127744575

In [26]:
x = b.view()
print(f"x:{x}\n\n b:{b}")

x:[[ 3  1  7 11]
 [ 2  8 13 21]]

 b:[[ 3  1  7 11]
 [ 2  8 13 21]]


In [35]:
b

array([[ 1,  3,  7, 11],
       [ 2,  8, 13, 21]])

In [42]:
b[-1:]

array([[ 2,  8, 13, 21]])

In [10]:
b = np.array([1,3,5,7])
z = np.zeros(4) #4 sütun 1 satırlık 0'lar matrisi
for i in range(4):
    z[i] = b[i]+8
z

array([ 9., 11., 13., 15.])

In [11]:
kedi = np.ones(5)
dog = np.zeros(5)
print(kedi); print(dog)

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]


In [12]:
print("ksdjfskdfjskdf")

ksdjfskdfjskdf


In [13]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [14]:
np.linspace(1,5,10) #3.paramtre vermezsek 5sütun10satır 50 sayı oluşturur.

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [15]:
np.full((4,4),5) #4x4 5'lerden oluşan matris oluşturur.

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [16]:
np.eye(5) # 5 birimlik birim matris

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.random((5,5))*10+5 # 5-15 arasında 5'e5lik random matris

array([[12.92276739,  5.62262352, 11.22013957, 13.39177507, 14.47151446],
       [11.55747116,  5.42457279,  7.43872343, 13.24945407,  5.54119542],
       [14.10661601,  8.02250504,  9.26166989,  7.12928447,  9.21862616],
       [14.13384713, 14.31459274, 13.42319299,  9.25991662, 12.77805059],
       [ 7.03158049,  9.25965414, 10.16007485,  6.49689125,  5.33460413]])

In [18]:
np.savetxt("arrayrandom.txt",a,delimiter=" ")

In [19]:
a = np.array([[3,5,7,11],[5,7,1,1]],dtype=np.int64)
a

array([[ 3,  5,  7, 11],
       [ 5,  7,  1,  1]], dtype=int64)

In [20]:
print("a'nın satır sütun sayısı: ",np.shape(a))

print("a'nın satır sayısı = len ", len(a))

print("a'nın toplam elemanı size",np.size(a))

print(a.dtype.name)

print("a'yı int'den floata çevireceğiz.", a.astype(np.float))


a'nın satır sütun sayısı:  (2, 4)
a'nın satır sayısı = len  2
a'nın toplam elemanı size 8
int64
a'yı int'den floata çevireceğiz. [[ 3.  5.  7. 11.]
 [ 5.  7.  1.  1.]]


#### Temel Matematiksel İşlemler

In [12]:
a = np.array([1,3,5,7])
b = np.array([2,4,6,8])

In [22]:
c = a+b; d = a*b; e = a/b
print(c)
print(d)
print(e)


[ 3  7 11 15]
[ 2 12 30 56]
[0.5        0.75       0.83333333 0.875     ]


In [13]:
a = np.array([1,3,5,7])
b = np.array([2,4,6,8])

In [14]:
np.multiply(a,b) # element bazında çarpım yapar a*b ile aynı

array([ 2, 12, 30, 56])

In [24]:
np.dot(a,b) # matris bazında çarpım yapar

100

In [15]:
np.sqrt(a) # karakök alır

array([1.        , 1.73205081, 2.23606798, 2.64575131])

In [26]:
a == b # a ve b'nin hangi elemanları birbirine eşit???
# araya >,<,!= vs gibi filtreler gelebilir.

array([False, False, False, False])

In [27]:
np.array_equal(a,b) # 2 matrisi direkt karşılaştırır.

False

In [16]:
print("Toplam:",a.sum()) # a arrayindeki elemanlar toplamı
print("Minimum Değer:",a.min())
print("Maxiumum Değer:",a.max())
print("Ortalama Değer:",a.mean())
print("Medyan:", np.median(a))
print("Standart Sapma:",np.std(a))

Toplam: 16
Minimum Değer: 1
Maxiumum Değer: 7
Ortalama Değer: 4.0
Medyan: 4.0
Standart Sapma: 2.23606797749979


In [29]:
a.mean() # a matrisindeki elemanların ortalamasını bulur

4.0

In [30]:
np.median(b) # b matrisinin medianı

5.0

In [31]:
np.std(a)

2.23606797749979

#### Array Kopyalama İşlemleri,Sorting ve Son Kısımlar

In [32]:
a = np.array([2,4,6,8])
b = a.view() # b=a yapsak da aynı mantık...
print(b)
c = a.copy()
print(c)

[2 4 6 8]
[2 4 6 8]


In [33]:
a[0] = 15 # a ile b aynı adreste tutulurlar bu nedenle a'daki değişiklik
# b'yi etkiler.
print(b)  
print(c) # ama copy işleminde farklı bir adreste tutulur.

[15  4  6  8]
[2 4 6 8]


In [32]:
a = np.array([[1,3,7,-2],[4,7,17,-21]])
print(a)

[[  1   3   7  -2]
 [  4   7  17 -21]]


In [18]:
a.sort() # axix = 0 yapmazsak satır bazlı sıralar.
print(a)

[[ -2   1   3   7]
 [-21   4   7  17]]


In [19]:
a.sort(axis=0) # Bu sefer sütun bazlı bir sıralama gerçekleşti.
a

array([[-21,   1,   3,   7],
       [ -2,   4,   7,  17]])

In [20]:
a[1,0] # ----> 1.boyutunun 0.indexi

-2

In [21]:
a[0,2] # ---> 0.boyutun 2.indexi

3

In [37]:
a[::-1] # ---> satırları ters çevir.
# eğer bunu tek boyutlu bir vektörde yapsaydık ters çevirirdik.

array([[ -2,   4,   7,  17],
       [-21,   1,   3,   7]])

In [38]:
filtre = a<2
filtre # a matrisinde 2'den küçük olanlar true olarak filtrelenir.

array([[ True,  True, False, False],
       [ True, False, False, False]])

In [39]:
a[filtre] #filtrede true olan değerler yazdırılır

array([-21,   1,  -2])

In [40]:
#aynı mantıkla filte yerine istediğimiz indexleri koyarsak da yazdırır.
b = np.array([1,3,5,7,11,12])
index = [0,1,3]
b[index]

array([1, 3, 7])

In [41]:
a.transpose() # ---> Veya a.T

array([[-21,  -2],
       [  1,   4],
       [  3,   7],
       [  7,  17]])

In [30]:
kilo = np.array([55,60,85,82,70,65,63,86,40,61])
kilo

array([55, 60, 85, 82, 70, 65, 63, 86, 40, 61])

In [31]:
kilo.reshape(10,1)

array([[55],
       [60],
       [85],
       [82],
       [70],
       [65],
       [63],
       [86],
       [40],
       [61]])

In [33]:
a = a.ravel() # vektör haline getirir.
a

array([  1,   3,   7,  -2,   4,   7,  17, -21])

In [34]:
a.reshape(4,2)

array([[  1,   3],
       [  7,  -2],
       [  4,   7],
       [ 17, -21]])

In [35]:
a.reshape(-1,2) #x satır 2 sütunlu hale getir dedik.

array([[  1,   3],
       [  7,  -2],
       [  4,   7],
       [ 17, -21]])

In [67]:
a = np.array([[1,3,7,-2],[4,7,17,-21]])
print(a)

[[  1   3   7  -2]
 [  4   7  17 -21]]


In [69]:
b = np.array([1,3,5,7,11,12])
b

array([ 1,  3,  5,  7, 11, 12])

In [70]:
np.append(a,100) # dizinin sonuna 100 değerini ekler 

array([  1,   3,   7,  -2,   4,   7,  17, -21, 100])

In [71]:
np.insert(a,2,173) # 2.indexe 173 değerini yazar 

array([  1,   3, 173,   7,  -2,   4,   7,  17, -21])

In [72]:
np.delete(a,1) # 

array([  1,   7,  -2,   4,   7,  17, -21])

In [73]:
b = np.array([-1,-2,-3])

In [74]:
np.concatenate((a,b)) # --> 2 arrayi birleştirirz.

ValueError: all the input arrays must have same number of dimensions

In [75]:
np.vstack((b,b)) # vertical yani dikey olarak aynı sütun sayısına sahip
            # birden fazla arrayi birleştirirz

array([[-1, -2, -3],
       [-1, -2, -3]])

In [52]:
np.hstack((a,a)) # aynı satır sayısına sahip 2 arrayi birleştirirz

array([[  1,   3,   7,  -2,   1,   3,   7,  -2],
       [  4,   7,  17, -21,   4,   7,  17, -21]])

In [53]:
a = np.arange(16).reshape(4,4)
a # 4x4 'lük' 0-16 arası matris oluştur.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
np.vsplit(a,2) # satıra göre 2 parçaya ayırır 2 farklı array oluşturur.

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [54]:
np.hsplit(a,2) # sütuna göre 2 parçaya böler ve 2 array oluşturur.

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

## Kurs Ödev ve Çözümler

In [55]:
#5 tane 1 barındıran bir array oluşturun
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [56]:
#2'den 100'e kadar olan değerlerden 2'ye tam bölünebilenlerle bir array oluşturun
#ve vektör haline getir.
x = np.arange(2,100,2)
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [57]:
#5 tane 10 bulunan bir array oluşturun
a = np.ones(5)*10
a

array([10., 10., 10., 10., 10.])

In [58]:
#1'den 16'ya kadar değer bulunduran 4x4'lük bir matris oluşturun
a = np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [59]:
a = np.linspace(1,5,20)
a

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [60]:
a = np.arange(1,101).reshape(10,10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [61]:
index= a>=41

In [62]:
a[index].reshape(-1,10)

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [63]:
a[4:]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [64]:
a[6:,4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [65]:
a[0:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [66]:
a[:3,1] # başka sütunlarda olsalar da aynı arrayde vektör olarak yazdırılır
     # çünkü matris olduğunu algılamıyor, kesişimlere bakılıyor. Bitiş değeri yok

array([ 2, 12, 22])

In [67]:
a[:3,1:2] # ama sütunun son değerini belirtirsek oranın sütun olduğunu anlar ve matrisdeki gibi yazar

array([[ 2],
       [12],
       [22]])

In [68]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [69]:
arr1

array([[3, 4, 2],
       [3, 3, 0],
       [4, 1, 4]])

In [70]:
arr2

array([[1, 0, 2],
       [0, 2, 3],
       [0, 3, 0]])

In [71]:
arr1+arr2

array([[4, 4, 4],
       [3, 5, 3],
       [4, 4, 4]])

In [72]:
arr1*arr2

array([[3, 0, 4],
       [0, 6, 0],
       [0, 3, 0]])

In [73]:
np.multiply(arr1,arr2)

array([[3, 0, 4],
       [0, 6, 0],
       [0, 3, 0]])

In [74]:
np.mean(arr1) # AO

2.6666666666666665